server:
  port: 8000


spring:
  application:
    name: 'study-java'
  datasource:
    #连接MySQL
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Ll0809double@
    driver-class-name: com.mysql.cj.jdbc.Driver
  groovy:
    template:
      check-template-location: false

mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true

debug: false
logging:
  path: /Users/xuling/Workspace/StudyJava/log







---
spring:
  profiles: dev
  application:
    name: 'study-java-dev'
server:
  port: 8080
